@startuml Groepnr 22
skinparam linetype ortho
Note as Info
  Voornamen: Ze, Marwan
  Groepnr: 22
  Gebruikte design pattern(s): Singleton Pattern
end Note

class SingletonDatabase{
  - {static} UniqueInstance : SingletonDatabase = new SingletonDatabase
  - SingletonDatabase()
  - {static} readonly SingletonDatabase()
  + {static} Instance() : SingletonDatabase
}

Class User{
    +User()
    +FirstName: string 
    +LastName: string
    +ID: int
}


interface IDataBase{
    +OpenConnection(): void 
    +SelectAllUsers(): List<User>
    +InsertUser(user: User): void
    +DeleteUser(user: User): void
    +IsConnected{get;}: bool
    +CloseConnection(): void
}

object Client
object MySQLDataBase

Client -- IDataBase
MySQLDataBase --> User
SingletonDatabase ..|> MySQLDataBase
IDataBase ..|> MySQLDataBase
IDataBase --o SingletonDatabase

@enduml