@startuml Groepnr 22
skinparam ClassAttributeIconSize 0
skinparam linetype ortho
Note as Info
  Voornamen: Ze, Marwan
  Groepnr: 22
  Gebruikte design pattern(s): Singleton Pattern
end Note

class SingletonDatabase{
  - instance : SingletonDatabase 
  - SingletonDatabase()
  ~ SingletonDatabase()
  + Instance{get;} : SingletonDatabase
  - db : MySQLDataBase
  + OpenConnection() : void
  + CloseConnection() : void
}
note right : Constructor and Destructor

Class User{
    + User()
    + FirstName: string 
    + LastName: string
    + ID: int
}


interface IDataBase{
    + OpenConnection(): void 
    + SelectAllUsers(): List<User>
    + InsertUser(user: User): void
    + DeleteUser(user: User): void
    + IsConnected{get;}: bool
    + CloseConnection(): void
}

object Client
class MySQLDataBase

IDataBase <|.. MySQLDataBase
MySQLDataBase <|-- SingletonDatabase
IDataBase <-- User
Client -- IDataBase


@enduml