@startuml Product
skinparam ClassAttributeIconSize 0

package domein{
    class Product{
        <- naam : String
        <-> prijsExclBtw : double
        <-> btwPercentage : int
        <-> kortingStuksPercentage : int
        + Product(naam : String, prijsExclBtw : double, kortingStuksPercentage : int)
        - setNaam(naam : String) : void
        + berekenPrijs(aantal : int) : double
    }
}

@enduml
